import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import static jdk.nashorn.internal.runtime.Debug.id;


/**
 *
 * @author SNDJ
 */
public class Accounts extends javax.swing.JFrame {

    private Object DbUtils;
  

    /**
     * Creates new form ViewAccounts
     */
    public Accounts() {
        initComponents();
            tableload();
    }
    RegisterFM rf = new RegisterFM();
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userId = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        fullnme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 204));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 520, 150, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserID", "Full Name", "Email", "User Type"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 550, 490));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Welcome to TechStore");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("UserID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 90, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Email Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Full Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("User Type:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 110, -1));

        userId.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        userId.setForeground(new java.awt.Color(255, 0, 0));
        userId.setText("UserID");
        getContentPane().add(userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 100, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 330, 50));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 330, 50));

        fullnme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnmeActionPerformed(evt);
            }
        });
        fullnme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fullnmeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fullnmeKeyTyped(evt);
            }
        });
        getContentPane().add(fullnme, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer-macbook-air-business-desktop.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 710));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
            
            int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete? ");
        
        if(x==0){
           
            String id = userId.getText();
            
            String sql = "DELETE FROM user WHERE id = '"+userId+"'";
            
            try{
                 pst = conn.prepareStatement(sql);
                pst.execute();
                
                tableload();
                
            }
            catch(Exception e){
                
            }
    }//GEN-LAST:event_deleteActionPerformed
    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int r = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
       
       
        String id1 = jTable2.getValueAt(r, 0).toString();
        String fn = jTable2.getValueAt(r, 1).toString();
        String em = jTable2.getValueAt(r, 2).toString();
        String ut = jTable2.getValueAt(r, 3).toString();
       
        rf.userId.setText(id1);
        rf.fullnme.setText(fn);
        rf.email.setText(em);
        rf.userType.setSelectedItem(ut);
      
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void fullnmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnmeActionPerformed

    private void fullnmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnmeKeyReleased
        /*
        String PATTERN = ("^[a-zA-Z0]{0,30}$");
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(fullnme.getText());
        if(!match.matches()){
            fnlab.setText("naming is incorrect");
        }
        else{
            fnlab.disable();

        }
        */

    }//GEN-LAST:event_fullnmeKeyReleased

    private void fullnmeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnmeKeyTyped
       

    }//GEN-LAST:event_fullnmeKeyTyped

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
       
    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped

    }//GEN-LAST:event_emailKeyTyped
                 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fullnme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel userId;
    // End of variables declaration//GEN-END:variables

    public void tableload() {
         try{
           
        String sql = "SELECT id,full_name,email,user_type FROM user";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        jTable2 = setModel(DbUtils.resultSetToTableModel(rs));
        
       }catch(Exception e){
           
       }
            
        
        
       
    }
}
