
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SNDJ
 */
public class LoginFM extends javax.swing.JFrame {

    /**
     * Creates new form LoginFM
     */
    public LoginFM() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1Rglink = new javax.swing.JLabel();
        LoginREset = new javax.swing.JButton();
        loginEM = new javax.swing.JTextField();
        logLogin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        loginPSWD = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 128, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Email Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 140, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 34, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 40, 40));

        jLabel1Rglink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1Rglink.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Rglink.setText("Click here to create a new account");
        jLabel1Rglink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1Rglink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1RglinkMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1Rglink, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        LoginREset.setBackground(new java.awt.Color(255, 153, 51));
        LoginREset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginREset.setText("Reset");
        LoginREset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginREsetActionPerformed(evt);
            }
        });
        getContentPane().add(LoginREset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 150, 60));
        getContentPane().add(loginEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 250, 50));

        logLogin.setBackground(new java.awt.Color(51, 51, 255));
        logLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logLogin.setText("Login");
        logLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logLoginActionPerformed(evt);
            }
        });
        getContentPane().add(logLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 150, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 110, 30));

        loginPSWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPSWDActionPerformed(evt);
            }
        });
        getContentPane().add(loginPSWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 250, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Welcome to TechStore");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Login Form");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 240, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer-macbook-air-business-desktop.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logLoginActionPerformed
        HttpConnector hc = new HttpConnector();
        User user;
        
             String em = loginEM.getText();
             String pswd = loginPSWD.getText();
             
           try{
                if((em.equals("") && pswd.equals(""))){
                    JOptionPane.showMessageDialog(null, "Please enter the login details!");
                }
             user = hc.login(loginEM.getText(), loginPSWD.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Login failure");
            return;
        }
        
        Homepage sp = new Homepage(user);
        sp.setVisible(true);
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logLoginActionPerformed

    private void LoginREsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginREsetActionPerformed
           loginEM.setText("");
           loginPSWD.setText("");
           LoginREset.setSelected(false);
    }//GEN-LAST:event_LoginREsetActionPerformed

    private void jLabel1RglinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1RglinkMouseClicked
        RegisterFM rg = new RegisterFM();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel1RglinkMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void loginPSWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPSWDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPSWDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginREset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1Rglink;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logLogin;
    private javax.swing.JTextField loginEM;
    private javax.swing.JPasswordField loginPSWD;
    // End of variables declaration//GEN-END:variables
}
